[package]
name = "log_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
rusqlite="0.30.0"
chrono="0.4.31"
plotters = "0.2.15"
# cairo = "*"